#!/bin/bash


clear


#INSTALACIÓN BASICA
BASICINST="menu message.txt ports.sh ADMbot.sh PGet.py usercodes sockspy.sh POpen.py PPriv.py PPub.py PDirect.py speedtest.py speed.sh utils.sh dropbear.sh apacheon.sh openvpn.sh shadowsocks.sh ssl.sh squid.sh"
IVAR="/etc/http-instas"



cabecalho_fun () {
BARRA="\033[0;34m========================================\033[0m"
BARRA2="\033[0;34m==============================================\033[0m"
BARRA3="\033[0;34m==================================================\033[0m"
echo -e "$BARRA"
echo "  KEYGEN" | figlet
echo -e "$BARRA"
cat << EOF
   ${BLANCO}INSTALACIONES NEW-ULTIMATE: $(cat $IVAR)
   ${BLANCO}INSTALACIONES KEY-GENERADOR: $(cat $IVAR)
EOF
SCPT_DIR="/etc/SCRIPT"
[[ ! -e ${SCPT_DIR} ]] && mkdir ${SCPT_DIR}
rm ${SCPT_DIR}/*.x.c &> /dev/null
INSTA_ARQUIVOS="ADMVPS.zip"
DIR="/etc/http-shell"
LIST="lista-arq"
}



meu_ip () {
MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MIP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
}


meu_ip
cabecalho_fun
fun_list () {
unset KEY
KEY="$1"
#CREAR DIRECTORIO Y ARCHIVOS
[[ ! -e ${DIR} ]] && mkdir ${DIR}
[[ ! -e ${DIR}/${KEY} ]] && mkdir ${DIR}/${KEY}


#ENVIAR ARCHIVOS
i=0
for arqx in `ls ${SCPT_DIR}`; do
[[ $(echo $BASICINST|grep -w "${arqx}") ]] && continue
echo -e "[$i] -> FERRAMENTA \033[1;31m[${arqx}]\033[0m"
arq_list[$i]="${arqx}"
let i++
done
echo -e " [x] -> TODAS LAS HERRAMIENTAS"
echo -e " [b] -> \033[1;33mINSTALACIÓN NEW-ULTIMATE BASICO\033[0m"
read -p " ESCOJE LOS ARCHIVOS: " readvalue
[[ -z $readvalue ]] && readvalue="b"
read -p " NOMBRE DEL USUARIO [ DUEÑO DE LA KEY ]: " nombrevalue
[[ -z $nombrevalue ]] && nombrevalue="unnamed"


read -p " KEY FIJA [S/N]: " -e -i n fixakey
[[ $fixakey = @(s|S|y|Y) ]] && read -p "IP-Fixo: " IPFIX && nombrevalue+=[FIXA]
if [[ $readvalue = @(b|B) ]]; then




#ADM BASIC
 arqslist="$BASICINST"
 for arqx in `echo "${arqslist}"`; do
 [[ -e ${DIR}/${KEY}/$arqx ]] && continue #ANULA ARQUIVO CASO EXISTA
 cp ${SCPT_DIR}/$arqx ${DIR}/${KEY}/
 echo "$arqx" >> ${DIR}/${KEY}/${LIST}
 done
elif [[ $readvalue = @(x|X) ]]; then



#FULL ARQS
 for arqx in `echo "${arq_list[@]}"`; do
  [[ -e ${DIR}/${KEY}/$arqx ]] && continue #ANULA ARQUIVO CASO EXISTA
  cp ${SCPT_DIR}/$arqx ${DIR}/${KEY}/
 echo "$arqx" >> ${DIR}/${KEY}/${LIST}
 done
echo "TRUE" >> ${DIR}/${KEY}/FERRAMENTA
else
 for arqx in `echo "${readvalue}"`; do
 
 
 
 #UNE ARCHIVOS
 [[ -e ${DIR}/${KEY}/${arq_list[$arqx]} ]] && continue #ANULA ARQUIVO CASO EXISTA
 cp ${SCPT_DIR}/${arq_list[$arqx]} ${DIR}/${KEY}/
 echo "${arq_list[$arqx]}" >> ${DIR}/${KEY}/${LIST}
 done
echo "TRUE" >> ${DIR}/${KEY}/FERRAMENTA
fi
echo "$nombrevalue" > ${DIR}/${KEY}.name
[[ ! -z $IPFIX ]] && echo "$IPFIX" > ${DIR}/${KEY}/keyfixa
echo -e "$BARRA"
echo -e "Key Ativa, e Aguardando Instalacao!"
echo -e "$BARRA"
}


#OFUSCAR KEY
ofus () {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="+";;
"+")txt[$i]=".";;
"1")txt[$i]="@";;
"@")txt[$i]="1";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"3")txt[$i]="%";;
"%")txt[$i]="3";;
"/")txt[$i]="K";;
"K")txt[$i]="/";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}

#GENERAR KEY
gerar_key () {
valuekey="$(date | md5sum | head -c10)"
valuekey+="$(echo $(($RANDOM*10))|head -c 5)"
fun_list "$valuekey"
keyfinal=$(ofus "$IP:8888/$valuekey/$LIST")
echo -e "KEY: $keyfinal\nGerada!"

echo -e " USUARIO: $nombrevalue $1\n KEY: $keyfinal $2\n FECHA: $(date "+%d/%m/%Y HORA: %H:%M:%S")\n KEYS RESTANTES: $(cat /etc/http-shell/$valuekey.name | wc -l)\n" >> /home/Admin/logs.txt

echo -e "$BARRA"
read -p "Enter to Finalize"
}

#ELIMINAR KEY
remover_key () {
i=0
[[ -z $(ls $DIR|grep -v "ERROR-KEY") ]] && return
echo "[$i] Retornar"
keys="$keys retorno"
let i++
for arqs in `ls $DIR|grep -v "ERROR-KEY"|grep -v ".name"`; do
arqsx=$(ofus "$IP:8888/$arqs/$LIST")
[[ $(cat ${DIR}/${arqs}.name|grep FIXA) ]] && echo -e "\033[1;33m[$i] $arqsx ($(cat ${DIR}/${arqs}.name))\033[1;32m ($(cat ${DIR}/${arqs}/keyfixa))\033[0m" || echo -e "[$i] $arqsx ($(cat ${DIR}/${arqs}.name))"
keys="$keys $arqs"
let i++
done
keys=($keys)
echo -e "$BARRA"
while [[ -z ${keys[$value]} || -z $value ]]; do
read -p "Escolha qual remover: " -e -i 0 value
done
[[ -d "$DIR/${keys[$value]}" ]] && rm -rf $DIR/${keys[$value]}* || return
}


#ACTUALIZAR KEY FIJA
atualizar_keyfixa () {
i=0
[[ -z $(ls $DIR|grep -v "ERROR-KEY") ]] && return
for arqs in `ls $DIR|grep -v "ERROR-KEY"|grep -v ".name"`; do
 if [[ $(cat ${DIR}/${arqs}.name|grep FIXA) ]]; then #Keyfixa Atualiza
   for arqx in `echo "${BASICINST}"`; do
    cp ${SCPT_DIR}/$arqx ${DIR}/${arqs}/$arqx
   done
 arqsx=$(ofus "$IP:8888/$arqs/$LIST")
 echo -e "\033[1;33m[KEY]: $arqsx \033[1;32m(ATUALIZADA!)\033[0m"
 fi
let i++
done
echo -e "$BARRA"
echo -ne "\033[0m" && read -p "Enter"
}

#INICIAR DETENER SERVIDOR
start_gen () {
unset PIDGEN
PIDGEN=$(ps aux|grep -v grep|grep "http-server.sh")
if [[ ! $PIDGEN ]]; then
screen -dmS generador /bin/http-server.sh -start
else
killall http-server.sh
fi
}




#MENSAJE KEYGEN
message_gen () {
read -p "NEW MESSAGE: " MSGNEW
echo "$MSGNEW" > ${SCPT_DIR}/message.txt
echo -e "$BARRA"
}



#ACTUALIZAR GENERADOR
atualizar_geb () {
wget -O $HOME/instger.sh https://www.dropbox.com/s/w0s2rv92wy7z3fq/instgerador.sh?dl=0 &>/dev/null
chmod +x $HOME/instger.sh
cd $HOME
./instger.sh
rm $HOME/instger.sh &>/dev/null
}


#COLORES
AMARILLO="\033[1;33m"
VERDE="\033[1;32m"
ROJO="\033[1;31m"
BLANCO="\033[1;37m"
AZUL="\033[0;34m"
CELESTE="\033[1;36m"



#MENU KEYGEN
meu_ip
unset PID_GEN
PID_GEN=$(ps x|grep -v grep|grep "http-server.sh")
[[ ! $PID_GEN ]] && PID_GEN="\033[1;31m[OFFLINE]" || PID_GEN="\033[1;32m[ONLINE]"

echo -e "$BARRA2"
echo -e " DIRECTORIO DE ARCHIVOS REPASADOS \033[1;31m${SCPT_DIR}\033[0m"
echo -e "$BARRA2"
echo -e " ${AZUL}[${BLANCO}01${AZUL}] ${CELESTE}= ${BLANCO}GENERAR KEY"
echo -e " ${AZUL}[${BLANCO}02${AZUL}] ${CELESTE}= ${BLANCO}ELIMINAR KEY"
echo -e " ${AZUL}[${BLANCO}03${AZUL}] ${CELESTE}= ${BLANCO}SERVIDOR $PID_GEN\033[0m"
echo -e " ${AZUL}[${BLANCO}04${AZUL}] ${CELESTE}= ${BLANCO}REGISTRO ${CELESTE}KEYS-FIJAS BLOQUEADAS"
echo -e " ${AZUL}[${BLANCO}05${AZUL}] ${CELESTE}= ${BLANCO}REGISTRO ${CELESTE}DETALLES KEYS"
echo -e " ${AZUL}[${BLANCO}06${AZUL}] ${CELESTE}= ${BLANCO}MODIFICAR MENSAJE"
echo -e " ${AZUL}[${BLANCO}07${AZUL}] ${CELESTE}= ${BLANCO}ACTUALIZAR KEY-FIJA"
echo -e " ${AZUL}[${BLANCO}08${AZUL}] ${CELESTE}= ${BLANCO}ACTUALIZAR KEY-GENERADOR"
echo -e " ${AZUL}[${BLANCO}09${AZUL}] ${CELESTE}= ${BLANCO}ACTUALIZAR GENERADOR"
echo -e " ${AZUL}[${BLANCO}00${AZUL}] ${CELESTE}= ${BLANCO}SALIR"

echo -e "$BARRA"
while [[ ${varread} != @([0-9]) ]]; do
read -p " OPCIÓN: " varread
done
echo -e "$BARRA3"

if [[ ${varread} = 1 ]]; then
gerar_key


elif [[ ${varread} = 2 ]]; then
remover_key


elif [[ ${varread} = 3 ]]; then
start_gen
read -p "ENTER"


elif [[ ${varread} = 4 ]]; then
echo -ne "\033[1;36m"
cat /etc/gerar-sh-log
echo -ne "\033[0m" && read -p " ENTER"


elif [[ ${varread} = 5 ]]; then
echo -e
echo -ne "\033[1;36m"
cat /home/Admin/logs.txt
echo -e "$BARRA3"
echo -ne "\033[0m" && read -p " ENTER"

elif [[ ${varread} = 6 ]]; then
message_gen

elif [[ ${varread} = 7 ]]; then
atualizar_keyfixa


elif [[ ${varread} = 8 ]]; then
atualizar_keyfixa

elif [[ ${varread} = 9 ]]; then
atualizar_geb


elif [[ ${varread} = 0 ]]; then
exit 0
fi
keygen
